#pragma once

#include <Arduino.h>
#include "Gfx.h"
#include "Theme.h"
#include "fonts/FontMetrics.h"

/* **********************************************************************************
    Text is DM Sans Bold -- the face the design specified -- embedded as TFT_eSPI smooth
    (anti-aliased) fonts generated by tools/make_vlw.py. Two sizes:

      FONT_SMALL  11px  door legends and every panel header. The door legends are
                        width-bound here: RIGHT FWD is 61px of ink in a 71px lamp, and
                        would need 66 at 12px.
      FONT_LARGE  14px  the IRS lamps, which have far more room.
      FONT_TINY    8px  small print on a lens, like MASTER CAUTION's PUSH TO RESET.

    A smooth font is loaded per TFT_eSPI object -- the tft and each sprite carry their own
    copy of the metrics -- so each sprite that draws text calls useFont() once.

    Measurements (cap height, advances, ink extent) do NOT come from the loaded font: they
    come from our own generated tables in fonts/. See fonts/FontMetrics.h for why. The
    PanelFont roles themselves are declared there too, beside the tables.
********************************************************************************** */

/* One line of a lamp legend. Lines of one lamp can mix sizes -- MASTER CAUTION carries
   PUSH TO RESET in small print under its main legend. */
struct LegendLine {
    const char *text;
    PanelFont   font;
};

namespace PanelGfx
{
    // Brings up the display. Pass 0 for backlightPin to skip backlight control.
    bool      begin(uint8_t backlightPin);
    Gfx::Device &tft();
    bool      ready();

    // The panel is lit only while MobiFlight is running (it has sent a value since the last
    // Stop), the bus feeding the annunciators is powered, and MobiFlight's power saving is
    // off. Otherwise the backlight is off. The brightness level applies while lit.
    void setBacklight(uint8_t level); // 0..255
    void setRunning(bool running);
    void setBusPowered(bool powered); // also ends the wait after waking
    void setPowerSave(bool on);
    // The boot splash's identify phase: lit regardless of the three above, so the panel
    // shows what the board is configured as. See Splash.h.
    void setIdentify(bool on);
    bool isLit();
    void tick(); // call regularly: ends the short settle delay after waking
    void setRotation(uint8_t rotation);

    /* Pushes a canvas to the screen at x,y. Panels go through this rather than calling
       the canvas directly, because on a framebuffered board it is also what records that
       the frame now differs from what the glass is showing. */
    void push(Gfx::Canvas &canvas, int16_t x, int16_t y);

    /* Sends the frame to the panel if anything has been drawn since the last time.
       Called once per poll from MFCustomDevice::update(). On a board that draws straight
       to its controller this costs nothing. */
    void present();

    void clearPanel();
    void clearRect(int16_t x, int16_t y, int16_t w, int16_t h);
    void drawRule(int16_t x, int16_t y, int16_t w, uint32_t colour);

    // Loads one of the embedded fonts onto the tft or a sprite (Gfx::Canvas is a Gfx::Device).
    void useFont(Gfx::Device &target, PanelFont font);

    // Panel headers, drawn straight to the TFT in FONT_SMALL. The design letter-spaces them,
    // which TFT_eSPI has no concept of, so they go down a character at a time. yMid is the
    // row the caps are centred on -- the same row as the rule beside them.
    void    drawSpacedText(int16_t x, int16_t yMid, const char *text, uint32_t fg, int16_t extraPx);
    int16_t spacedTextWidth(const char *text, int16_t extraPx);

    // Renders one lamp filling the whole of `spr`; the caller pushes it. `font` is the
    // font the sprite has loaded -- it is what the legend is measured against. Legends are
    // centred on their inked extent, or start at padLeft.
    void renderLamp(Gfx::Canvas &spr, const LampStyle &st, PanelFont font,
                    const char *l1, const char *l2,
                    bool centered, int16_t padLeft);

    // The general form: any LampKind, up to four centred lines, each in its own font.
    // `loaded` is the font the sprite has loaded now; it is switched only when a line needs
    // another, and updated to whatever is loaded on return.
    // `pressed` draws the lamp as a button held down: the relief and the gradient turn
    // over and the legend moves with the cap.
    void renderLampLines(Gfx::Canvas &spr, const LampStyle &st,
                         const LegendLine *lines, uint8_t count, PanelFont &loaded,
                         bool pressed = false);

    /* A plate: the face a group of lights is set into, drawn straight to the screen.
       `raised` when it is something you press -- a six-pack -- which then stands proud and
       goes in when `pressed`. A plate that only holds lights is drawn flat. */
    void drawPlate(int16_t x, int16_t y, int16_t w, int16_t h, int16_t radius,
                   uint32_t fill, uint32_t edge, bool raised, bool pressed);

    // A 1px outline `inset` px outside a rectangle, or the panel background to erase it.
    void drawRing(int16_t x, int16_t y, int16_t w, int16_t h, int16_t inset, uint32_t colour);
}
