// Generated by tools/make_vlw.py -- do not edit.
//
// DM Sans Bold 15 glyph metrics: ink box, advance and bearings per character.
// Safe to include anywhere -- inline constexpr, so the linker keeps one copy and a
// measurement used only in a static_assert costs no flash at all.
#pragma once

#include "FontMetrics.h"

inline constexpr GlyphMetric DMSansBold15_glyphs[] = {
    // code    w    h  adv   dX   dY
    {'(',   6,  14,   6,   0,  12},
    {')',   6,  14,   6,   0,  12},
    {'+',   8,   7,   9,   0,   8},
    {'-',   7,   2,   9,   1,   6},
    {'.',   4,   2,   4,   0,   2},
    {'/',   7,  14,   6,   0,  12},
    {'0',  10,  10,  10,   0,  10},
    {'1',   5,  10,   6,   0,  10},
    {'2',   9,  10,   9,   0,  10},
    {'3',   9,  10,   9,   0,  10},
    {'4',  10,  10,  10,   0,  10},
    {'5',   8,  10,   9,   1,  10},
    {'6',   9,  10,  10,   0,  10},
    {'7',   8,  10,   8,   0,  10},
    {'8',   9,  10,  10,   0,  10},
    {'9',   9,  10,  10,   0,  10},
    {':',   4,   8,   4,   0,   8},
    {'A',  11,  10,  11,   0,  10},
    {'B',   8,  10,  10,   1,  10},
    {'C',  11,  10,  11,   0,  10},
    {'D',   9,  10,  10,   1,  10},
    {'E',   8,  10,   9,   1,  10},
    {'F',   7,  10,   8,   1,  10},
    {'G',  11,  10,  12,   0,  10},
    {'H',   9,  10,  11,   1,  10},
    {'I',   3,  10,   4,   1,  10},
    {'J',   8,  10,   8,   0,  10},
    {'K',   9,  10,  10,   1,  10},
    {'L',   7,  10,   9,   1,  10},
    {'M',  12,  10,  13,   1,  10},
    {'N',   9,  10,  11,   1,  10},
    {'O',  11,  10,  11,   0,  10},
    {'P',   8,  10,   9,   1,  10},
    {'Q',  11,  12,  11,   0,  10},
    {'R',   8,  10,  10,   1,  10},
    {'S',   9,  10,   9,   0,  10},
    {'T',   9,  10,   9,   0,  10},
    {'U',  10,  10,  10,   0,  10},
    {'V',  11,  10,  11,   0,  10},
    {'W',  15,  10,  15,   0,  10},
    {'X',  10,  10,  10,   0,  10},
    {'Y',  10,  10,  10,   0,  10},
    {'Z',   9,  10,   9,   0,  10},
    {'_',   9,   2,  10,   1,   0},
};

inline constexpr FontMetrics DMSansBold15Metrics = {
    DMSansBold15_glyphs, 44, 15, 4, 10, 11, 3,
};
