// Generated by tools/make_vlw.py -- do not edit.
//
// DM Sans Bold 11 glyph metrics: ink box, advance and bearings per character.
// Safe to include anywhere -- inline constexpr, so the linker keeps one copy and a
// measurement used only in a static_assert costs no flash at all.
#pragma once

#include "FontMetrics.h"

inline constexpr GlyphMetric DMSansBold11_glyphs[] = {
    // code    w    h  adv   dX   dY
    {'(',   5,  11,   5,   0,   9},
    {')',   4,  11,   5,   0,   9},
    {'+',   6,   5,   6,   0,   6},
    {'-',   6,   3,   6,   0,   5},
    {'.',   3,   2,   3,   0,   2},
    {'/',   5,  10,   5,   0,   9},
    {'0',   7,   8,   7,   0,   8},
    {'1',   4,   8,   4,   0,   8},
    {'2',   7,   8,   7,   0,   8},
    {'3',   7,   8,   7,   0,   8},
    {'4',   7,   8,   7,   0,   8},
    {'5',   7,   8,   7,   0,   8},
    {'6',   7,   8,   7,   0,   8},
    {'7',   6,   8,   6,   0,   8},
    {'8',   7,   8,   7,   0,   8},
    {'9',   7,   8,   7,   0,   8},
    {':',   3,   6,   3,   0,   6},
    {'A',   8,   8,   8,   0,   8},
    {'B',   7,   8,   7,   0,   8},
    {'C',   8,   8,   8,   0,   8},
    {'D',   8,   8,   8,   0,   8},
    {'E',   6,   8,   7,   0,   8},
    {'F',   6,   8,   6,   0,   8},
    {'G',   8,   8,   9,   0,   8},
    {'H',   8,   8,   8,   0,   8},
    {'I',   3,   8,   3,   0,   8},
    {'J',   6,   8,   6,   0,   8},
    {'K',   7,   8,   7,   0,   8},
    {'L',   6,   8,   6,   0,   8},
    {'M',   9,   8,  10,   0,   8},
    {'N',   8,   8,   8,   0,   8},
    {'O',   8,   8,   8,   0,   8},
    {'P',   7,   8,   7,   0,   8},
    {'Q',   8,   9,   8,   0,   8},
    {'R',   7,   8,   7,   0,   8},
    {'S',   7,   8,   7,   0,   8},
    {'T',   7,   8,   7,   0,   8},
    {'U',   7,   8,   8,   0,   8},
    {'V',   8,   8,   8,   0,   8},
    {'W',  11,   8,  11,   0,   8},
    {'X',   7,   8,   7,   0,   8},
    {'Y',   7,   8,   7,   0,   8},
    {'Z',   6,   8,   7,   0,   8},
};

inline constexpr FontMetrics DMSansBold11Metrics = {
    DMSansBold11_glyphs, 43, 11, 3, 8, 8, 2,
};
