// Generated by tools/make_vlw.py -- do not edit.
//
// DM Sans Bold 14 glyph metrics: ink box, advance and bearings per character.
// Safe to include anywhere -- inline constexpr, so the linker keeps one copy and a
// measurement used only in a static_assert costs no flash at all.
#pragma once

#include "FontMetrics.h"

inline constexpr GlyphMetric DMSansBold14_glyphs[] = {
    // code    w    h  adv   dX   dY
    {'(',   6,  14,   6,   0,  12},
    {')',   6,  14,   6,   0,  12},
    {'+',   8,   7,   8,   0,   8},
    {'-',   6,   2,   8,   1,   6},
    {'.',   4,   2,   4,   0,   2},
    {'/',   6,  14,   6,   0,  12},
    {'0',   9,  10,   9,   0,  10},
    {'1',   5,  10,   6,   0,  10},
    {'2',   8,  10,   8,   0,  10},
    {'3',   8,  10,   9,   0,  10},
    {'4',   9,  10,   9,   0,  10},
    {'5',   7,  10,   9,   1,  10},
    {'6',   8,  10,   9,   0,  10},
    {'7',   8,  10,   8,   0,  10},
    {'8',   8,  10,   9,   0,  10},
    {'9',   9,  10,   9,   0,  10},
    {':',   4,   7,   4,   0,   7},
    {'A',  10,  10,  10,   0,  10},
    {'B',   8,  10,   9,   1,  10},
    {'C',  10,  10,  10,   0,  10},
    {'D',   8,  10,  10,   1,  10},
    {'E',   7,  10,   8,   1,  10},
    {'F',   7,  10,   8,   1,  10},
    {'G',  11,  10,  11,   0,  10},
    {'H',   9,  10,  10,   1,  10},
    {'I',   2,  10,   4,   1,  10},
    {'J',   7,  10,   8,   0,  10},
    {'K',   8,  10,   9,   1,  10},
    {'L',   7,  10,   8,   1,  10},
    {'M',  11,  10,  12,   1,  10},
    {'N',   9,  10,  10,   1,  10},
    {'O',  10,  10,  11,   0,  10},
    {'P',   8,  10,   9,   1,  10},
    {'Q',  10,  12,  11,   0,  10},
    {'R',   8,  10,   9,   1,  10},
    {'S',   8,  10,   9,   0,  10},
    {'T',   9,  10,   8,   0,  10},
    {'U',   9,  10,  10,   0,  10},
    {'V',  10,  10,  10,   0,  10},
    {'W',  14,  10,  14,   0,  10},
    {'X',   9,  10,   9,   0,  10},
    {'Y',   9,  10,   9,   0,  10},
    {'Z',   8,  10,   8,   0,  10},
    {'_',   8,   2,  10,   1,   0},
};

inline constexpr FontMetrics DMSansBold14Metrics = {
    DMSansBold14_glyphs, 44, 14, 4, 10, 11, 3,
};
