// Generated by tools/make_vlw.py -- do not edit.
//
// DM Sans Bold 8 glyph metrics: ink box, advance and bearings per character.
// Safe to include anywhere -- inline constexpr, so the linker keeps one copy and a
// measurement used only in a static_assert costs no flash at all.
#pragma once

#include "FontMetrics.h"

inline constexpr GlyphMetric DMSansBold8_glyphs[] = {
    // code    w    h  adv   dX   dY
    {'(',   3,   9,   3,   0,   8},
    {')',   3,   9,   3,   0,   8},
    {'+',   5,   4,   5,   0,   5},
    {'-',   4,   2,   5,   0,   3},
    {'.',   2,   2,   2,   0,   2},
    {'/',   4,   9,   3,   0,   8},
    {'0',   6,   7,   5,   0,   7},
    {'1',   3,   7,   3,   0,   7},
    {'2',   5,   7,   5,   0,   7},
    {'3',   5,   7,   5,   0,   7},
    {'4',   5,   7,   5,   0,   7},
    {'5',   5,   7,   5,   0,   7},
    {'6',   5,   7,   5,   0,   7},
    {'7',   5,   7,   4,   0,   7},
    {'8',   5,   7,   5,   0,   7},
    {'9',   5,   7,   5,   0,   7},
    {':',   2,   5,   2,   0,   5},
    {'A',   6,   7,   6,   0,   7},
    {'B',   5,   7,   5,   0,   7},
    {'C',   6,   7,   6,   0,   7},
    {'D',   6,   7,   6,   0,   7},
    {'E',   5,   7,   5,   0,   7},
    {'F',   5,   7,   5,   0,   7},
    {'G',   6,   7,   6,   0,   7},
    {'H',   6,   7,   6,   0,   7},
    {'I',   2,   7,   2,   0,   7},
    {'J',   4,   7,   4,   0,   7},
    {'K',   6,   7,   5,   0,   7},
    {'L',   5,   7,   5,   0,   7},
    {'M',   7,   7,   7,   0,   7},
    {'N',   6,   7,   6,   0,   7},
    {'O',   6,   7,   6,   0,   7},
    {'P',   5,   7,   5,   0,   7},
    {'Q',   6,   8,   6,   0,   7},
    {'R',   5,   7,   5,   0,   7},
    {'S',   5,   7,   5,   0,   7},
    {'T',   5,   7,   5,   0,   7},
    {'U',   5,   7,   5,   0,   7},
    {'V',   6,   7,   6,   0,   7},
    {'W',   8,   7,   8,   0,   7},
    {'X',   6,   7,   5,   0,   7},
    {'Y',   5,   7,   5,   0,   7},
    {'Z',   5,   7,   5,   0,   7},
};

inline constexpr FontMetrics DMSansBold8Metrics = {
    DMSansBold8_glyphs, 43, 8, 2, 7, 7, 2,
};
