// Generated by tools/make_vlw.py -- do not edit.
//
// The 320-wide panel's font set. Include fonts/FontSet.h rather than this directly:
// it picks the set that matches the board being built.
#pragma once

#include "FontMetrics.h"
#include "DMSansBold11.h"
#include "DMSansBold11Metrics.h"
#include "DMSansBold14.h"
#include "DMSansBold14Metrics.h"
#include "DMSansBold8.h"
#include "DMSansBold8Metrics.h"

inline constexpr FontMetrics PANEL_FONTS[PANEL_FONT_COUNT] = {
    DMSansBold11Metrics, // FONT_SMALL -- 11px
    DMSansBold14Metrics, // FONT_LARGE -- 14px
    DMSansBold8Metrics, // FONT_TINY -- 8px
};

inline constexpr const FontMetrics &fontOf(PanelFont f) { return PANEL_FONTS[f]; }

// The font data itself, in the .vlw layout the display libraries parse. Which blob
// backs which role is generated here so no backend has to name a pixel size.
inline constexpr const uint8_t *const PANEL_FONT_BLOBS[PANEL_FONT_COUNT] = {
    DMSansBold11, // FONT_SMALL
    DMSansBold14, // FONT_LARGE
    DMSansBold8, // FONT_TINY
};

inline constexpr const uint8_t *blobOf(PanelFont f) { return PANEL_FONT_BLOBS[f]; }
