// Generated by tools/make_vlw.py -- do not edit.
//
// The 480-wide panel's font set. Include fonts/FontSet.h rather than this directly:
// it picks the set that matches the board being built.
#pragma once

#include "FontMetrics.h"
#include "DMSansBold15.h"
#include "DMSansBold15Metrics.h"
#include "DMSansBold19.h"
#include "DMSansBold19Metrics.h"
#include "DMSansBold11.h"
#include "DMSansBold11Metrics.h"

inline constexpr FontMetrics PANEL_FONTS[PANEL_FONT_COUNT] = {
    DMSansBold15Metrics, // FONT_SMALL -- 15px
    DMSansBold19Metrics, // FONT_LARGE -- 19px
    DMSansBold11Metrics, // FONT_TINY -- 11px
};

inline constexpr const FontMetrics &fontOf(PanelFont f) { return PANEL_FONTS[f]; }

// The font data itself, in the .vlw layout the display libraries parse. Which blob
// backs which role is generated here so no backend has to name a pixel size.
inline constexpr const uint8_t *const PANEL_FONT_BLOBS[PANEL_FONT_COUNT] = {
    DMSansBold15, // FONT_SMALL
    DMSansBold19, // FONT_LARGE
    DMSansBold11, // FONT_TINY
};

inline constexpr const uint8_t *blobOf(PanelFont f) { return PANEL_FONT_BLOBS[f]; }
