#pragma once

/* Picks the font set that matches the screen being built for.

   The resolution comes from Board.h, so a board picks its font sizes by picking itself.
   The sets themselves are generated by tools/make_vlw.py -- see FONT_SETS there. */

#include "Board.h"

#if ANNUN_PANEL_RES == 480
#include "FontSet480.h"
#else
#include "FontSet320.h"
#endif
