#pragma once

/* Picks the logo that matches the screen being built for, as fonts/FontSet.h does for the
   fonts. Both are generated by tools/make_logo.py from art/boeing-737-800-silhouette.png;
   that image's attribution and licence (CC BY-SA 4.0) are in each header. */

#include "Board.h"

#if ANNUN_PANEL_RES == 480
#include "Logo480.h"
#else
#include "Logo320.h"
#endif
