#!/usr/bin/env python3
"""Convert the boot splash logo to RGB565 C arrays, one per screen resolution.

The splash (Annunciator/Splash/Splash.cpp) draws the logo a pixel at a time from these
headers. They are committed, so this is only needed to change the image, its size or its
colour.

    .venv/bin/pip install pillow
    .venv/bin/python tools/make_logo.py                    # regenerate
    .venv/bin/python tools/make_logo.py --colour B8BEC6    # the same, recoloured
    .venv/bin/python tools/make_logo.py --check            # fail if the headers are stale

The image is "Boeing 737-800 silhouette" by Peter James Lowden, from Wikimedia Commons
(https://commons.wikimedia.org/wiki/File:Boeing_737-800_silhouette.svg), under CC BY-SA 4.0
(https://creativecommons.org/licenses/by-sa/4.0/). art/boeing-737-800-silhouette.png is the
960px rendering Commons publishes of it. Cropping, scaling, flattening and reducing it to
RGB565 makes the headers an adaptation, which is CC BY-SA 4.0 as well -- the headers say so,
and so does art/README.md.
"""

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is missing: .venv/bin/pip install pillow")

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "art" / "boeing-737-800-silhouette.png"
OUT_DIR = ROOT / "Annunciator" / "Splash"

# The square each screen's logo is fitted into, in pixels. Splash.cpp lays the screen out
# round the same numbers (LOGO_BOX) and static_asserts that the logo fits; change both
# together. 160 is 120 x 4/3: the two screens are the same height in millimetres, so this
# keeps the logo the same size in the hand.
BOXES = {320: 120, 480: 160}

# Theme::PanelBg. The logo is flattened onto it here, so its anti-aliased edge is already
# blended and the firmware only has to copy pixels.
BACKGROUND = (0, 0, 0)

ATTRIBUTION = """\
// "Boeing 737-800 silhouette" by Peter James Lowden, from Wikimedia Commons
// (https://commons.wikimedia.org/wiki/File:Boeing_737-800_silhouette.svg), CC BY-SA 4.0
// (https://creativecommons.org/licenses/by-sa/4.0/).
//
// Changes: cropped to the aircraft, scaled to {w}x{h},{recolour} flattened onto the panel
// background and reduced to RGB565, by tools/make_logo.py. This adaptation is licensed
// CC BY-SA 4.0 as well."""


def to565(r, g, b):
    """Exactly Theme::to565(): truncate, as every other colour on the panel is."""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def load(colour):
    image = Image.open(SOURCE).convert("RGBA")
    image = image.crop(image.getchannel("A").getbbox())  # the aircraft, not the canvas
    if colour:
        # A silhouette is its alpha: keep the shape and its smooth edge, change the paint.
        solid = Image.new("RGBA", image.size, colour + (255,))
        solid.putalpha(image.getchannel("A"))
        image = solid
    return image


def scaled(image, box):
    w, h = image.size
    scale = min(box / w, box / h)
    size = (max(1, round(w * scale)), max(1, round(h * scale)))
    # Premultiplied, so the transparent pixels' colour cannot bleed into the edge as a fringe.
    return image.convert("RGBa").resize(size, Image.LANCZOS).convert("RGBA")


def pixels565(image):
    out = []
    for r, g, b, a in image.getdata():
        blend = lambda c, bg: (c * a + bg * (255 - a) + 127) // 255
        out.append(to565(blend(r, BACKGROUND[0]), blend(g, BACKGROUND[1]),
                         blend(b, BACKGROUND[2])))
    return out


def header(res, image, values, colour):
    w, h = image.size
    rows = ["    " + ", ".join("0x%04X" % v for v in values[i:i + 16]) + ","
            for i in range(0, len(values), 16)]
    recolour = " recoloured #%02X%02X%02X," % colour if colour else ""
    attribution = ATTRIBUTION.format(w=w, h=h, recolour=recolour)
    return f"""// Generated by tools/make_logo.py from art/{SOURCE.name} -- do not edit.
//
{attribution}
//
// The {res}-wide panel's logo. Include LogoSet.h rather than this directly: it picks the
// one that matches the board being built.
#pragma once

#include <stdint.h>

namespace Logo
{{
constexpr int16_t  W = {w}, H = {h};
constexpr uint16_t BACKGROUND = 0x{to565(*BACKGROUND):04X}; // pixels of this value are not drawn

// RGB565 as Theme::to565() makes it, row-major, top row first.
inline constexpr uint16_t PIXELS[W * H] = {{
{chr(10).join(rows)}
}};
}} // namespace Logo
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--colour", help="recolour the silhouette, as RRGGBB")
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed headers differ from a fresh conversion")
    args = ap.parse_args()

    colour = None
    if args.colour:
        try:
            value = int(args.colour.lstrip("#"), 16)
        except ValueError:
            sys.exit("--colour takes RRGGBB, e.g. B8BEC6")
        colour = ((value >> 16) & 0xFF, (value >> 8) & 0xFF, value & 0xFF)

    image = load(colour)
    stale = []
    for res, box in BOXES.items():
        logo = scaled(image, box)
        text = header(res, logo, pixels565(logo), colour)
        path = OUT_DIR / ("Logo%d.h" % res)
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(path.name)
            continue
        path.write_text(text)
        print("%s  %dx%d in a %dpx box, %d bytes of pixels"
              % (path.name, logo.size[0], logo.size[1], box, 2 * logo.size[0] * logo.size[1]))
    if stale:
        sys.exit("out of date: %s -- rerun tools/make_logo.py (with the same --colour)"
                 % ", ".join(stale))


if __name__ == "__main__":
    main()
